default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: codecoach_development
  host: localhost

test:
  <<: *default
  database: codecoach_test

production:
  adapter: postgresql
  host: localhost
  port: 5432
  database: codecoach_production
