# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45761457b26182b7b9d2bb767a105f7d8e66e0cae4aad84f5248cb655c1b8d770ed7d2ec93db0b6fe46543d906e93d06a9fee90060e664848e96af13d7c4ea64

test:
  secret_key_base: 7fc5889e81fed66e8d502f0e300e381bbadd4f1ede03cdf9f16df18bd3affdb759f874004f44ec688f7e269bb8da8b41535455da70f3de0f769e0e8bf5c6f2c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
